ProjectTrackerWPF/ProjectTrackerMVC/Controllers/OsobasController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Input;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.PlatformUI;
using ProjectTracker.BusinessLibrary.Core.Models;
using ProjectTracker.Dal;

namespace ProjectTrackerMVC.Controllers
{
    public class OsobasController : Controller
    {
        private bool _novi;
        private string _ime;
        private string _prezime;

        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyRaised(string propertyname)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyname));
            }
        }

        private ICommand _newOsobaCommand;
        private ICommand _editOsobaCommand;
        private ICommand _saveOsobaCommand;
        public async Task<IActionResult> Index()
        {
            return View(ListaOsoba);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        public async Task<IActionResult> Edit()
        {
            Osoba osobaa;
            osobaa = Osoba.New();
            osobaa.Ime = "Luka";
            osobaa.Prezime = "Peric";
            return View(osobaa);
        }
        public async Task<IActionResult> Delete()
        {
            Osoba osobaa;
            osobaa = Osoba.New();
            osobaa.Ime = "Luka";
            osobaa.Prezime = "Peric";
            return View(osobaa);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ime,Prezime")]Osoba osoba)
        {
            Osoba osobaa;
            osobaa = Osoba.New();
            osobaa.Ime = osoba.Ime;
            osobaa.Prezime = osoba.Prezime;
            Osoba o = osobaa.Save();
            ListaOsoba = OsobaInfoList.Get();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var osoba = Lookup.FetchOsoba(id);
            if (osoba == null)
            {
                return NotFound();
            }

            return View(osoba);
        }

        public ICommand NovaOsobaCommand
        {
            get { return _newOsobaCommand ?? (_newOsobaCommand = new DelegateCommand(DodajOsobu)); }
        }

        public ICommand EditOsobaCommand
        {
            get { return _editOsobaCommand ?? (_editOsobaCommand = new DelegateCommand(UrediOsobu)); }
        }

        public ICommand SpremiOsobuCommand
        {
            get { return _saveOsobaCommand ?? (_saveOsobaCommand = new DelegateCommand(SpremiOsobu)); }
        }

        public string Ime
        {
            get { return _ime; }
            set { _ime = value; }
        }

        public string Prezime
        {
            get { return _prezime; }
            set { _prezime = value; }
        }

        public string PunoIme
        {
            get { return Ime + " " + Prezime; }
        }

        public bool MozeSpremit { get; set; } = false;
        public bool IsReadOsoba { get; set; } = true;

        public OsobaInfoList ListaOsoba { get; set; } = OsobaInfoList.Get();
        List<ProjectTracker.Dal.DatabaseModels.Osoba> osobe { get; set; } = Lookup.FetchOsobe();

        public OsobaInfo SelektiranaOsoba { get; set; }
        private void DodajOsobu()
        {
            _novi = true;
            Ime = String.Empty;
            Prezime = String.Empty;
            IsReadOsoba = false;
            MozeSpremit = true;
            OnPropertyRaised("Ime");
            OnPropertyRaised("Prezime");
            OnPropertyRaised("MozeSpremit");
            OnPropertyRaised("IsReadOsoba");
        }

        private void UrediOsobu()
        {
            _novi = false;
            Ime = SelektiranaOsoba.Ime;
            Prezime = SelektiranaOsoba.Prezime;
            IsReadOsoba = false;
            MozeSpremit = true;
            OnPropertyRaised("Ime");
            OnPropertyRaised("Prezime");
            OnPropertyRaised("MozeSpremit");
            OnPropertyRaised("IsReadOsoba");
        }

        private void SpremiOsobu()
        {
            Osoba osoba;
            if (_novi)
            {
                osoba = Osoba.New();
                osoba.Ime = Ime;
                osoba.Prezime = Prezime;
                ProjectTracker.BusinessLibrary.Core.Models.Osoba o = osoba.Save();
            }
            else
            {
                osoba = Osoba.Get(SelektiranaOsoba.Id);
                osoba.Ime = Ime;
                osoba.Prezime = Prezime;
                Osoba.Update(osoba);
            }
            MozeSpremit = false;
            IsReadOsoba = true;
            OnPropertyRaised("Ime");
            OnPropertyRaised("Prezime");
            OnPropertyRaised("MozeSpremit");
            OnPropertyRaised("IsReadOsoba");
            Ime = Prezime = String.Empty;
            ListaOsoba = OsobaInfoList.Get();
            OnPropertyRaised("ListaOsoba");
        }


    }
}

ProjectTrackerWPF/ProjectTrackerMVC/Controllers/ProjektsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectTracker.BusinessLibrary.Core.Models;

namespace ProjectTrackerMVC.Controllers
{
    public class ProjektsController : Controller
    {
        private readonly ProjectTracker.Dal.ProjektFERContext _context;
        private bool _novi;
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public DateTime? Zapocet { get; set; }
        public DateTime? Zavrsen { get; set; }
        public ProjektInfoList ListaProjekata { get; set; } = ProjektInfoList.Get();
        List<ProjectTracker.Dal.DatabaseModels.Projekt> projekti { get; set; } = ProjectTracker.Dal.Lookup.FetchProjekte();

        // GET: Projekts
        public async Task<IActionResult> Index()
        {
            return View(ListaProjekata);
        }

        // GET: Projekts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            foreach (var item in ListaProjekata)
            {
                if(item.Id == id)
                {
                    Naziv = item.Naziv;
                    Opis = item.Opis;
                    Zapocet = item.Zapocet;
                    Zavrsen = item.Zavrsen;
                }
            }

            return View();
        }

        // GET: Projekts/Create
        public IActionResult Create()
        {
            return View();
        }
       
        // POST: Projekts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Opis,Zapocet,Zavrsen")] Projekt projekt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projekt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(projekt);
        }

       

        // POST: Projekts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
       
    }
}

ProjectTrackerWPF/ProjectTrackerMVC/Controllers/UlogasController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Input;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.PlatformUI;
using ProjectTracker.BusinessLibrary.Core.Models;
namespace ProjectTrackerMVC.Controllers
{
    public class UlogasController : Controller
    {
        private bool _novi;
        private ICommand _dodajUloguCommand;
        private ICommand _urediUloguCommand;
        private ICommand _spremiUloguCommand;

        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyRaised(string propertyname)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyname));
            }
        }
        public ICommand UrediUloguCommand
        {
            get { return _urediUloguCommand ?? (_urediUloguCommand = new DelegateCommand(UrediUlogu)); }
        }

        public ICommand NovaUlogaCommand
        {
            get { return _dodajUloguCommand ?? (_dodajUloguCommand = new DelegateCommand(DodajUlogu)); }
        }

        public ICommand SpremiUloguCommand
        {
            get { return _spremiUloguCommand ?? (_spremiUloguCommand = new DelegateCommand(SpremiUlogu)); }
        }
        public UlogaInfoList ListaUloga { get; set; } = UlogaInfoList.Get();
        // GET: Ulogas
        public async Task<IActionResult> Index()
        {
            return View(ListaUloga);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv")]Uloga uloga)
        {
            Uloga ulogaa;
            ulogaa = Uloga.New();
            ulogaa.Naziv = uloga.Naziv;
            Uloga u = ulogaa.Save();
            ListaUloga = UlogaInfoList.Get();
            return RedirectToAction(nameof(Index));
        }
        public string Naziv { get; set; } = String.Empty;
        public bool MozeSpremit { get; set; } = false;
        public bool IsReadUloga { get; set; } = true;

        public UlogaInfo SelektiranaUloga { get; set; }
        private void UrediUlogu()
        {
            _novi = false;
            Naziv = SelektiranaUloga.Naziv;
            MozeSpremit = true;
            IsReadUloga = false;
            OnPropertyRaised("Naziv");
            OnPropertyRaised("MozeSpremit");
            OnPropertyRaised("IsReadUloga");
        }

        private void DodajUlogu()
        {
            _novi = true;
            Naziv = String.Empty;
            MozeSpremit = true;
            IsReadUloga = false;
            OnPropertyRaised("MozeSpremit");
            OnPropertyRaised("IsReadUloga");
        }

        private void SpremiUlogu()
        {
            Uloga uloga;
            if (_novi)
            {
                uloga = Uloga.New();
                uloga.Naziv = Naziv;
                Uloga u = uloga.Save();
            }
            else
            {
                uloga = Uloga.Get(SelektiranaUloga.Id);
                uloga.Naziv = Naziv;
                Uloga.Update(uloga);
            }

            MozeSpremit = false;
            IsReadUloga = true;
            OnPropertyRaised("Naziv");
            OnPropertyRaised("MozeSpremit");
            OnPropertyRaised("IsReadUloga");
            var bu = uloga.GetBrokenRules();
            Naziv = String.Empty;
            ListaUloga = UlogaInfoList.Get();
            OnPropertyRaised("ListaUloga");
        }
    

}       
}

ProjectTrackerWPF/ProjectTrackerMVC/Views/Shared/Info.cshtml
@model ProjectTracker.Dal.DatabaseModels.Osoba

@{
    ViewData["Title"] = "Info";
}

<h1>Info</h1>

<div>
    <h4>Osoba</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

ProjectTrackerWPF/ProjectTrackerMVC/Views/Shared/Popis.cshtml
@model IEnumerable<ProjectTracker.Dal.DatabaseModels.Osoba>

@{
    ViewData["Title"] = "Popis";
}

<h1>Popis</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
        </tr>
}
    </tbody>
</table>

ProjectTrackerWPF/ProjectTrackerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectTrackerMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectTrackerMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Osobas" asp-action="Index">Popis osoba</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projekts" asp-action="Index">Popis projekata</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ulogas" asp-action="Index">Popis uloga</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ProjectTrackerMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>